apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USERNAME: "camila"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  API_KEY: "super-secreta"  # reemplaza en Jenkins si prefieres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend
          image: localhost:8082/backend-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-test
  ports:
    - name: http-node
      port: 3000
      targetPort: 3000
    - name: http-java
      port: 8080
      targetPort: 8080
  type: ClusterIP
